
<div>
	<?php $productCollection =$block->getProductCollection();?>	
	<table>
		<thead>
			<tr>	
				<th colspan="2"> 
					Random Product 
				</th>		
			</tr>
		</thead>
		<tbody>	
			<?php foreach ($productCollection as $product): ?>	
					<tr>
						<td>
						    <a href="<?= $product->getProductUrl()?>">						
								<img src="<?=$block->getImageUrl($product);?>" />								
							</a>
						</td>
						<td>
						<a class="simple-text" href="<?= $product->getProductUrl()?>">
							<p>
								<?=$product->getData('name');?>
							</p>
							<strong>
								<?=$product->getFormattedPrice($product->getData('price'));?>
							</strong>
						</a>								
						</td>						
					</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>